### ISSUE TITLE
prevent multiple getrawtransaction / txinfo on known txid

### ISSUE THREAD

**Issue by backpacker69** [PeerAssets/chizukeki#14]
after turning on debug console, you can see that chizukeki app requests same transactions with  getrawtransactions/txinfo every time it syncs.

**Comment by backpacker69** [comment]
for example, my address has  13 transactions with it, explorer gets hammered 13 times with requests for getrawtransaction and txinfo.

**Comment by micimize** [comment]
closed by 3514c88a60f570e92c915c5bf3db66dafb8b64fe, which will only fetch transactions until they have 10 confirmations (easily changeable)
