### ISSUE TITLE
gracefully deal with explorer errors

### ISSUE THREAD

**Issue by backpacker69** [PeerAssets/chizukeki#19]
currently chizukeki just stops completely after getting an error from explorer/papi

**Comment by micimize** [comment]
@backpacker69 can I get more details as to what you mean by "stops completely"? The current expected behavior for a failed sync is for the button to display a "Failure" red button, and then retry the next time the sync is triggered, either manually or automatically.

**Comment by backpacker69** [comment]
it's fine, I understand it now.
