### ISSUE TITLE
new wallet without any transactions shows block 0 seen a minute ago and not synching

### ISSUE THREAD

**Issue by backpacker69** [PeerAssets/chizukeki#35]
newly generated wallet without any transactions shows block 0 seen a minute ago and not synching until you send coins to it and manually refresh.

**Comment by peerchemist** [comment]
It's papi thing, papi is not serving the stuff properly now for some reason.

**Comment by saeveritt** [comment]
@peerchemist I dont believe Chizu queries papi for last seen block information.

**Comment by backpacker69** [comment]
error persists:

![image](https://user-images.githubusercontent.com/19201340/42410843-7d8e04a8-81f9-11e8-8732-2561e5971094.png)
