### ISSUE TITLE
Allow mulitple inputs per card transaction

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/chizukeki#36]
Adding new recipients currently replaces the [existing one.](https://i.imgur.com/x1BoBWJ.png)

**Comment by peerchemist** [comment]
PA card transfer can take up to 40 recipients.

**Comment by micimize** [comment]
@saeveritt this seems to only happen when I try to send to the same address twice.
<img width="481" alt="screen shot 2018-07-04 at 12 37 40" src="https://user-images.githubusercontent.com/8343799/42289794-190b1738-7f87-11e8-8623-dc7812203048.png">

@peerchemist went ahead and added a limit in 72914a8ecce1e847dc2559f7398a9b47f1fb13c2

**Comment by micimize** [comment]
closing as I'm fairly sure it's not an issue. IMO replacing the current amount for the same address in the amounts map is sensible, although having an indicator that that is going to happen would be nice
