### ISSUE TITLE
Display transaction amount + fee in outgoing transactions

### ISSUE THREAD

**Issue by bananenwilly** [PeerAssets/chizukeki#38]
![image](https://user-images.githubusercontent.com/11148913/42330429-74a884b2-8073-11e8-9d36-d74e2aa79013.png)

or I'm bad at math.

**Comment by peerchemist** [comment]
Duplicate of: https://github.com/PeerAssets/chizukeki/issues/32

**Comment by bananenwilly** [comment]
#32 deals with excessive fees, this issue is a display issue. 

0.11 TPPC have been payed, not 0.01 and the displayed balance is correct, only the transaction log is wrong.

**Comment by micimize** [comment]
right, I guess we should display `-${amount + fee}` and show `amount: ${amount}, fee: ${fee}` in the expanded details
