### ISSUE TITLE
Chizukeki falsely reports the incoming balance with the CardTransfer transaction

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/chizukeki#45]
![screenshot from 2018-07-21 14-09-44](https://user-images.githubusercontent.com/7818961/43035438-d9699b56-8cef-11e8-8efc-52564ebda8d8.png)

Chizukeki shows +0.02 PPC as incoming balance. Check the transaction: https://chainz.cryptoid.info/ppc-test/tx.dws?414698353033127b556444dc5a2a3c10a1e5761d451b2899de00aee61ace09f3.htm

It deposits 0 PPC at the receiving address.
Also, fee is not 0.02 but 0.01.

**Comment by micimize** [comment]
The fee according to chainz is 0.02 also. I'm guessing bitcore gave it that fee for the size of the op return, because of the newly introduced dynamic fees
