### ISSUE TITLE
Don't shorten the txid, it makes debugging harder

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/chizukeki#48]
![screenshot from 2018-07-22 11-28-53](https://user-images.githubusercontent.com/7818961/43044213-80bbb904-8da2-11e8-8aa4-433abc632bc5.png)

**Comment by micimize** [comment]
if you select and copy the id, it copies the whole id, not just the truncated part (related to #16). At least that's how it is in my testing (mac, chrome). If we really need the entire id visible I guess I could make the detail area scroll

**Comment by peerchemist** [comment]
Ok I did not realize that.
