### ISSUE TITLE
synch failed (:ERR_CERT_DATE_INVALID)

### ISSUE THREAD

**Issue by bananenwilly** [PeerAssets/chizukeki#51]
The currently deployed version tries to contact explorer.peercoin.net:8000/api/getblockcount? which results in an invalid cert error. Thus chizukeki is not syncing. 

> state after dispatch Object
> explorer.peercoin.net:8000/ext/getaddress/mnrpyUA4NPnQePbZwQLViUrZmTwg5J4Tkc:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
> bundle.js:101 will dispatch Object
> bundle.js:101 state after dispatch Object
> explorer.peercoin.net:8000/api/getblockcount?:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
> bundle.js:101 TypeError: Failed to fetch
> (anonymous) @ bundle.js:101
> bundle.js:101 will dispatch Object
> bundle.js:101 state after dispatch Object
> explorer.peercoin.net:8000/ext/getaddress/mnrpyUA4NPnQePbZwQLViUrZmTwg5J4Tkc:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
> bundle.js:101 will dispatch Object
> bundle.js:101 state after dispatch Object
> bundle.js:101 TypeError: Failed to fetch
> (anonymous) @ bundle.js:101
> explorer.peercoin.net:8000/api/getblockcount?:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
> wallet:1 Failed to load resource: the server responded with a status of 404 ()
> bundle.js:101 will dispatch {type: "SYNC_WALLET_STARTED", payload: {…}, Symbol(@@redux-saga/SAGA_ACTION): true}
> bundle.js:101 state after dispatch {wallet: {…}, assets: {…}, router: {…}}
> bundle.js:101 will dispatch {type: "SYNC_WALLET_FAILED", payload: {…}, error: true, Symbol(@@redux-saga/SAGA_ACTION): true}
> bundle.js:101 GET https://explorer.peercoin.net:8000/ext/getaddress/mnrpyUA4NPnQePbZwQLViUrZmTwg5J4Tkc 0 ()
>

**Comment by peerchemist** [comment]
It's using the wrong URL of explorer.

Correct URL is testnet-explorer.peercoin.net

**Comment by micimize** [comment]
fix deployed - would be more accurate to say the url was changed.

**Comment by peerchemist** [comment]
Surprised we did not catch this in the logs. URL was changed a long long time before.
